import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

import apiV1Sidebar from './docs/api/v1/paths/sidebar';
import apiV2Sidebar from './docs/api/v2/paths/sidebar';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  apiV1Sidebar: [
    {
      id: 'api/v1/getting-started',
      label: 'Getting started',
      type: 'doc',
    },
    {
      items: [
        {
          dirName: 'api/v1/concepts',
          type: 'autogenerated',
        },
      ],
      label: 'Concepts',
      type: 'category',
    },
    {
      defaultStyle: true,
      type: 'html',
      value: '<hr style="margin: 8px 0;" />',
    },
    ...apiV1Sidebar,
  ],
  apiV2Sidebar: [
    {
      id: 'api/v2/getting-started',
      label: 'Getting started',
      type: 'doc',
    },
    ...apiV2Sidebar,
  ],
  contributingSidebar: [{ dirName: 'contributing', type: 'autogenerated' }],
};

export default sidebars;
